baseURL: https://612969a9edce7724ff3cb337--alphoncina-allielyamuya.netlify.app/
languageCode: en-us
title: Minimal
theme: minimal
disqusShortname: username
googleAnalytics: ''
params:
  accent: red
  author: Calin Tataru
  backgroundColor: white
  description: Personal blog theme powered by Hugo
  font: Raleway
  githubUsername: '#'
  highlight: yes
  highlightLanguages:
    - go
    - haskell
    - kotlin
    - scala
    - swift
  highlightStyle: default
  showBorder: yes
menu:
  icon:
    - name: fas fa-envelope
      url: mailto:alyamuya257@gmail.com
      weight: 1
    - name: fab fa-github
      url: https://github.com/alyamuya257/
      weight: 2
    - name: fab fa-twitter
      url: https://twitter.com/Aalyamuya/
      weight: 3
    - name: fab fa-linkedin
      url: https://www.linkedin.com/in/alphoncinalyamuya/
      weight: 4
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Posts
      url: /post/
      weight: 3
    - name: Projects
      url: /project/
      weight: 4
