baseURL: https://612969a9edce7724ff3cb337--alphoncina-allielyamuya.netlify.app/
languageCode: en-us
title: Alphoncina (Allie) Lyamuya
theme: minimal
disqusShortname: username
googleAnalytics: ''
params:
  accent: blueviolet 
  author: Allie Lyamuya 
  backgroundColor: white
  description: Welcome, and thank you for being here!
  font: Times
  relativeURLs: true
  githubUsername: '#'
  enableEmoji: true
  profilePic: "coding.jpeg/"
  post: "/:year/:month/:day/:slug/"
  highlight: yes
  highlightLanguages:
    - go
    - haskell
    - kotlin
    - scala
    - swift
  highlightStyle: default
  showBorder: yes
menu:
  icon:
    - name: fas fa-envelope
      url: mailto:alyamuya257@gmail.com
      weight: 1
    - name: fab fa-github
      url: https://github.com/alyamuya257/
      weight: 2
    - name: fab fa-twitter
      url: https://twitter.com/Aalyamuya/
      weight: 3
    - name: fab fa-linkedin
      url: https://www.linkedin.com/in/alphoncinalyamuya/
      weight: 4
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Posts
      url: /post/
      weight: 3
    - name: Projects
      url: /project/
      weight: 4
